
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LabSes1.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Activity
{

    public int Id { get; set; }

    public string Login { get; set; }

    public Nullable<System.DateTime> TimeLogin { get; set; }

    public Nullable<bool> SuccessLogin { get; set; }

}

}
